import { createElement } from 'lwc';
import Ia_VolunteerBooking from 'c/ia_VolunteerBooking';

describe('c-ia-volunteer-booking', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ia-volunteer-booking', {
            is: Ia_VolunteerBooking
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});